apiVersion: v1
kind: ConfigMap
metadata:
  name: envoy-config
  namespace: envoy-authz-poc
data:
  envoy.yaml: |
    admin:
      access_log:
        - name: access_log_file
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
            path: "/dev/stdout"
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 9901

    node:
      id: envoy-poc
      cluster: envoy-cluster

    static_resources:
      listeners:
        - name: main_listener
          address:
            socket_address:
              protocol: TCP
              address: 0.0.0.0
              port_value: 8080
          filter_chains:
            - filters:
                - name: envoy.filters.network.http_connection_manager
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                    codec_type: auto
                    stat_prefix: ingress_http
                    access_log:
                      - name: envoy.access_loggers.stdout
                        typed_config:
                          "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
                    route_config:
                      name: local_route
                      virtual_hosts:
                        - name: backend
                          domains: ["*"]
                          routes:
                            - match:
                                prefix: "/health"
                              direct_response:
                                status: 200
                                body:
                                  inline_string: "healthy"
                              typed_per_filter_config:
                                envoy.filters.http.ext_authz:
                                  "@type": type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthzPerRoute
                                  disabled: true
                            - match:
                                prefix: "/v1/data"
                              route:
                                cluster: opa
                              typed_per_filter_config:
                                envoy.filters.http.ext_authz:
                                  "@type": type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthzPerRoute
                                  disabled: true
                            - match:
                                prefix: "/api"
                              route:
                                cluster: echo-server
                                prefix_rewrite: "/"
                            - match:
                                prefix: "/"
                              route:
                                cluster: echo-server
                    http_filters:
                      - name: envoy.filters.http.ext_authz
                        typed_config:
                          "@type": type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz
                          transport_api_version: V3
                          with_request_body:
                            max_request_bytes: 8192
                            allow_partial_message: true
                          failure_mode_allow: false
                          grpc_service:
                            envoy_grpc:
                              cluster_name: opa-envoy
                            timeout: 1s
                      - name: envoy.filters.http.router
                        typed_config:
                          "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router

      clusters:
        - name: echo-server
          connect_timeout: 1s
          type: STRICT_DNS
          lb_policy: ROUND_ROBIN
          load_assignment:
            cluster_name: echo-server
            endpoints:
              - lb_endpoints:
                  - endpoint:
                      address:
                        socket_address:
                          address: 127.0.0.1
                          port_value: 80

        - name: opa
          connect_timeout: 1s
          type: STRICT_DNS
          lb_policy: ROUND_ROBIN
          load_assignment:
            cluster_name: opa
            endpoints:
              - lb_endpoints:
                  - endpoint:
                      address:
                        socket_address:
                          address: 127.0.0.1
                          port_value: 8181

        - name: opa-envoy
          type: STRICT_DNS
          connect_timeout: 1s
          lb_policy: ROUND_ROBIN
          http2_protocol_options: {}
          load_assignment:
            cluster_name: opa-envoy
            endpoints:
              - lb_endpoints:
                  - endpoint:
                      address:
                        socket_address:
                          address: 127.0.0.1
                          port_value: 9191

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: opa-config
  namespace: envoy-authz-poc
data:
  config.yaml: |
    plugins:
      envoy_ext_authz_grpc:
        addr: :9191
        enable_reflection: true

    decision_logs:
      console: true

    status:
      console: true

  authz.rego: |
    package envoy.authz
    import rego.v1

    default allow := false

    allow if {
        token := input.attributes.request.http.headers.authorization
        startswith(token, "Bearer ")
        token == "Bearer test-token"
    }

    allow if {
        input.attributes.request.http.headers.authorization == "Bearer admin-token"
    }

    allow if {
        public_paths := {"/health", "/v1/data"}
        input.attributes.request.http.path in public_paths
    }

    allow if {
        input.attributes.request.http.method == "GET"
        token := input.attributes.request.http.headers.authorization
        startswith(token, "Bearer ")
        token != ""
    }
