apiVersion: v1
kind: Service
metadata:
  name: envoy-entrypoint
  namespace: envoy-authz-poc
spec:
  selector:
    app: envoy-ext-authz-opa
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  - name: admin
    port: 9901
    targetPort: 9901
  type: LoadBalancer
